# Basic config
baseURL = "https://ReubenDemirdjian.github.io/website/"
theme = "hugo-simple"
defaultContentLanguage = "en"
languageCode = "en"                # zh-Hans
title = "Reuben Demirdjian"
mainSections = ["blog"]

#Step 5 from https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorcontentbasename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Hugo Simple"
description = "Hugo Simple Demo"
favicon = "images/wave1.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = true

[params.author]
name = "Reuben Demirdjian"
email = "ReubenDemi@gmail.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Blog"
pageRef = "/blog"
weight = 20
[[menu.main]]
name = "CV"
pageRef = "/cv"
weight = 20

[services.rss]
limit = 42

[pagination]
pagerSize = 32

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]

